#spring:
#  thymeleaf:
#    cache: false
#  datasource:
#    username: root
#    password: 1q2w3e
#    url: jdbc:mysql://localhost:3306/test?useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.mysql.cj.jdbc.MysqlDataSource